### PR TITLE
SEAMCATCH-29 testcase

### PR DESCRIPTION
**Pull request by jharting**
I've made a testcase to reproduce SEAMCATCH-29. Provided my understanding of Catch is valid, it reproduces a bug in Catch.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Jozef, this is a great test case. Thank you for putting it together.

It's missing one piece though. We need a descending handler for the super type, to ensure it gets executed at the correct time.

Unfortunately, our explanation of the ordering has caused confusion. So we've come up with a better terminology for the traversal modes that I think will make it a lot clearer.

See these two JIRAs:
- https://issues.jboss.org/browse/SEAMCATCH-31
- https://issues.jboss.org/browse/SEAMCATCH-32

**Comment by jharting** [comment]
Dan, I fixed the name of the exception and added the handler. Nevertheless, I still think the order currently implemented in Catch is not the intended one. See my comment on https://issues.jboss.org/browse/SEAMCATCH-31?focusedCommentId=12571093#comment-12571093

**Comment by mojavelinux** [comment]
Right, I know. When we address the two issues related to this test, then we will use the test to ensure the order we expect is the order implemented. So we can't fix it yet since the behavior needs to change anyway. But we will fix it.

**Comment by LightGuard** [comment]
I've integrated these (sorry Dan, didn't see you added a test, I did as well from Jozef's original request).

**Pull request closed without merging**
