### PR TITLE
Functional tests

### PR DESCRIPTION
**Pull request by mgencur**
Hi Jason, this is a functional test for basic-servlet example. I also created a pom.xml which will go to examples directory and that contains dependencies needed for running the functional tests. The same was recently done for seam Security and Remoting module, and will be done for other modules as well. It there appears a new example in the future, we'll add only the test then, not any additional pom files. Look at the readme.txt how to run the tests. Note that I used 3.0.0.Beta2 version since the current version specified in the module sources is this one.

Martin

### CODE REVIEW

**Comment by LightGuard** [comment]
Couple of things: the license in Catch is APL, I'll need to modify some of the files to reflect that. All of the other tests in Catch are using JUnit, do you mind if I change the tests to use JUnit instead of TestNG (for consistency)?

**Comment by mgencur** [comment]
I have time so I will do these things ;-) Then I will send you another pull request.

**Comment by LightGuard** [comment]
Just make the new commits, GitHub will pick them up and add them to this pull request. No need for a new one :)

**Comment by mgencur** [comment]
Jason, I was able only to change the licensing. We are currently using JBoss project called richfaces-selenium which is designed for testNG, but perhaps in a month we'll be able to switch to a new version of the project called Ajocado, which will have the integration with junit if I ask the developer to create it. So it's not possible to use junit at the moment.

**Comment by LightGuard** [comment]
Okay, that's fine. Thanks!

**Comment by LightGuard** [comment]
I may have to play with this a bit more, I tried running the tests and it just sat there.

**Comment by mgencur** [comment]
Hmm, that's strange. I just tested it here. You have to deploy the application into running JBossAS before running the tests.  Or you can run it with -Pjbossas-remote-6,ftest which will deploy the app instead of you. But the JBossAS still has to be running. Where is it stuck?

**Comment by LightGuard** [comment]
running the tests, I'll try again later and let you know.

**Comment by mgencur** [comment]
OK, you might ran it in a wrong directory. You have to run it in examples/basic-servlet/.

**Comment by LightGuard** [comment]
Yep, still hangs running the TestSuite, no output, nothing :(

**Comment by mgencur** [comment]
What type of OS do you have? We are running it on Linux. You also have to have Firefox browser installed.

**Comment by LightGuard** [comment]
Mac OSX Snow Leopard. Was using Safari.

**Comment by mgencur** [comment]
I think that will be the reason. Selenium is not able to work with all browser and systems. IIRC, on Mac OSX it never worked, at least what I was told by Pete. If you are able to try it on linux, please do it. But in my case it worked.

**Comment by mgencur** [comment]
Jason, as Shane stated, we are going to move the definition of the ftest maven profile somewhere higher up into different pom.xml. I suggest letting this pull request open and when I move it to the desired location (which I don't know right now where it will be) I'll do another commit. Then you can merge it. Do you agree? But I think it won't work with Mac OS anyway. This is mainly for QA purposes and people are not supposed to run the tests on a regular basis. So I think it doesn't have to be 100% portable, and I think it's not even possible now.

**Comment by LightGuard** [comment]
Yes, that's fine. As for Selenium and Macs, I know more current versions work fine with it, so it may be the version of selenium being used.

**Comment by mgencur** [comment]
Jason, could you please try to replace the following lines in the examples/pom.xml and run the tests? This should ensure using the newest version of selenium. I don't have access to any Mac OS

Replace
<plugin>
       <groupId>org.codehaus.mojo</groupId>
        <artifactId>selenium-maven-plugin</artifactId>
        <version>1.0.1</version>
</plugin>  
with
<plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>selenium-maven-plugin</artifactId>
        <version>1.1</version>
</plugin>

If this doesn't help then I don't know what:) Remember to have Firefox browser installed, I don't know if this should work with safari. For sure, the configuration is set up for Firefox.

Thanks

**Comment by LightGuard** [comment]
Nope, still hangs on Mac OSX :(

**Comment by mgencur** [comment]
Jason, this is the refactored configuration for running functional tests. The main config is in seam-parent now. I also updated the selenium-maven-plugin to version 1.1. There is not any newer version. I wonder if you can run the functional tests now. It is configured to run with Firefox web browser. If you don't have it installed, it won't work.

**Comment by mgencur** [comment]
There is another pull requests which replaced this one.

**Pull request closed without merging**
